import Link from "next/link";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import type { Service } from "@/data/services";
import { siteConfig } from "@/data/site";

export function ServicePage({ service }: { service: Service }) {
  return <><Header /><main id="main">
    <section className="service-hero-v3"><div className="service-hero-grid" aria-hidden="true" /><div className="shell service-hero-v3-shell"><div className="service-breadcrumbs"><Link href="/">Главная</Link><span>/</span><Link href="/services">Практики</Link><span>/</span><span>{service.breadcrumb}</span></div><div className="service-hero-v3-layout"><div className="service-hero-v3-copy"><span className="kicker kicker-on-dark">Практика {service.index}</span><h1>{service.title}</h1><p>{service.intro}</p><div className="service-hero-actions"><Link className="button button-copper" href="/consultation">{service.ctaLabel} <span>↗</span></Link><a className="text-link text-link-light" href={`tel:${siteConfig.phone}`}>{siteConfig.phoneDisplay}</a></div></div><aside className="service-brief"><span className="service-brief-index">{service.index}</span><div className="service-brief-meta">{service.meta.map((item) => <div key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div><div className="service-brief-foot"><span>Аутсорсинг ДВ</span><span>Хабаровск · ДФО</span></div></aside></div></div></section>
    <section className="section service-content-v3"><div className="shell service-content-v3-layout"><aside className="service-toc"><span className="kicker">Содержание</span><nav>{service.sections.map((section,index) => <a key={section.id} href={`#${section.id}`}><span>0{index+1}</span>{section.navLabel}</a>)}</nav><div className="service-toc-contact"><span>Консультация</span><strong>{siteConfig.consultationPrice}</strong><Link href="/consultation">Записаться ↗</Link></div></aside><div className="service-article">{service.sections.map((section,index) => <section className="service-block" id={section.id} key={section.id}><div className="service-block-index">0{index+1}</div><div className="service-block-copy"><h2>{section.title}</h2>{section.lead ? <p className="service-lead">{section.lead}</p> : null}{section.items?.length ? <ul className="service-list">{section.items.map((item) => <li key={item}>{item}</li>)}</ul> : null}{section.notice ? <div className="service-notice"><span>Важно</span><div><strong>{section.notice.title}</strong><p>{section.notice.text}</p></div></div> : null}</div></section>)}</div></div></section>
    <section className="section service-cta-v3"><div className="shell service-cta-v3-layout"><div><span className="kicker kicker-on-dark">Следующий шаг</span><h2>{service.cta.title}</h2><p>{service.cta.text}</p></div><div className="service-cta-v3-actions"><Link className="button button-ice" href="/consultation">{service.cta.primary} <span>↗</span></Link><a className="text-link text-link-light" href={`tel:${siteConfig.phone}`}>Позвонить {siteConfig.phoneDisplay}</a></div></div></section>
  </main><Footer /></>;
}
